"""Added Cost and Payment Table

Revision ID: 24a68202ebbd
Revises: a02e9f6c7e40
Create Date: 2022-07-14 21:55:11.792292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a68202ebbd'
down_revision = 'a02e9f6c7e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobsRun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobName', sa.String(), nullable=True),
    sa.Column('runTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobsRun_id'), 'jobsRun', ['id'], unique=False)
    op.create_table('storeSummaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('isIncrease', sa.Boolean(), nullable=True),
    sa.Column('percentValue', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storeSummaries_id'), 'storeSummaries', ['id'], unique=False)
    op.create_table('orderCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('totalCost', sa.Float(), nullable=True),
    sa.Column('generatedBy', sa.Integer(), nullable=True),
    sa.Column('dateGenerated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['generatedBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderCost_id'), 'orderCost', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('amountPaid', sa.Float(), nullable=True),
    sa.Column('paymentType', sa.String(), nullable=False),
    sa.Column('modifyBy', sa.Integer(), nullable=True),
    sa.Column('paidBy', sa.String(), nullable=False),
    sa.Column('transactionId', sa.String(), nullable=False),
    sa.Column('datePaid', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['modifyBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orderCost_id'), table_name='orderCost')
    op.drop_table('orderCost')
    op.drop_index(op.f('ix_storeSummaries_id'), table_name='storeSummaries')
    op.drop_table('storeSummaries')
    op.drop_index(op.f('ix_jobsRun_id'), table_name='jobsRun')
    op.drop_table('jobsRun')
    # ### end Alembic commands ###
