"""Added Cost and Payment Table

Revision ID: 6451ba0c11b0
Revises: 9b804fa543a8
Create Date: 2022-07-14 23:08:36.422306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6451ba0c11b0'
down_revision = '9b804fa543a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('totalCost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amountPaid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('modifyBy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dateModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], name='accounts_companyId_fkey'),
    sa.ForeignKeyConstraint(['modifyBy'], ['users.id'], name='accounts_modifyBy_fkey'),
    sa.PrimaryKeyConstraint('id', name='accounts_pkey')
    )
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###
