"""Balance field added to payment

Revision ID: 93e98c4c90f6
Revises: 6451ba0c11b0
Create Date: 2022-07-19 23:04:54.171123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e98c4c90f6'
down_revision = '6451ba0c11b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'balance')
    # ### end Alembic commands ###
